### ISSUE TITLE
About demo

### ISSUE THREAD

**Issue by trinhtuanvubk** [TAU-VAILab/HaLo-NeRF#1]
where can I get the code of illustrated demo in project page ? thank you so much

**Comment by chendudai** [comment]
As explained here: https://github.com/TAU-VAILab/HaLo-NeRF/blob/main/docs/evaluation.md, use the eval.py code for creating the NeRF. Use the --images_ids flag to specify which images to use, and --num_frames flag to indicate how many frames are between the images.

For changing the appearace use the eval_appearance.py code as described in this file as well:
https://github.com/TAU-VAILab/HaLo-NeRF/blob/main/docs/evaluation.md
